# Copyright (c) 2026 Nokia
# SPDX-License-Identifier: BSD-3-Clause
# Kind cluster configuration for the helm integration scenarios (smoke, swap,
# llm-tier). The node image is pinned by version and digest so every machine
# creates the same cluster (eng01-kind-test-demo-rig); the digest is the
# default node image of kind v0.32.0.
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.36.1@sha256:3489c7674813ba5d8b1a9977baea8a6e553784dab7b84759d1014dbd78f7ebd5
