# Copyright (c) 2026 Nokia
# SPDX-License-Identifier: BSD-3-Clause
# ollama disabled but no external endpoint (MeshView.Validate not-in-cluster branch).
ollama:
  enabled: false
llm:
  externalURL: ""
